version: "3.8"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      # 데이터베이스 설정
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://192.168.120.1:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      # 관리자 계정 설정
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command: start-dev

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_SERVER_ROOT_URL=http://192.168.120.1:3000
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - keycloak

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
