auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /data/loki/wal  # WAL 디렉토리 변경
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Consul 대신 인메모리 사용
      replication_factor: 1

compactor:
  working_directory: /data/loki/compactor
  shared_store: filesystem

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

limits_config:
  enforce_metric_name: false

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s