global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8888'] # OpenTelemetry Collector zPages
  - job_name: 'host-metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9464'] # Host metrics from Collector